name: Add Triage member

on:
  issues:
    types: [opened]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: ./invite2org
      name: Adds user as contribtor
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        repository: ${{ GITHUB_REPOSITORY }}
        username: ${{ GITHUB_ACTOR }}
        team_slug: 'issue-triage'


