name: Add Triage member

on:
  issues:
    types: [opened]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
     - uses: actions/checkout@v1
     - uses: ./invite2org
      name: Adds user as contribtor
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        repository: ${{ env.GITHUB_REPOSITORY }}
        username: ${{ env.GITHUB_ACTOR }}
        team_slug: 'issue-triage'


